### ISSUE TITLE
Whitelisting and volumes 

### ISSUE THREAD

**Issue by lordraiden** [coreruleset/modsecurity-crs-docker#149]
I have spend many hours troubleshooting and I need to ask...

This is my compose file

```
  modsecurity:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: ProxyDMZ-ModSecurity
    restart: unless-stopped
    networks:
      - netmodsecurity
    volumes:
      - /mnt/user/Docker/WebProxyDMZ/ModSecurity/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - /mnt/user/Docker/WebProxyDMZ/ModSecurity/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      #- /mnt/user/Docker/WebProxyDMZ/ModSecurity:/etc/modsecurity.d/owasp-crs/rules
      #- /mnt/user/Docker/WebProxyDMZ/ModSecurity/auditlogs:/dev/stdout
      #- /mnt/user/Docker/WebProxyDMZ/ModSecurity/data:/tmp/modsecurity/data
    environment:
      # ModSecurity ENV Variables
      # CRS specific variables
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=5
      - BACKEND=http://dummy

  dummy:
    image: traefik/whoami
    container_name: ProxyDMZ-ModSecurity-Dummy
    restart: unless-stopped
    networks:
      - netmodsecurity
```

I have been trying to whitelist this
to parse it https://jsonformatter.org/json-parser

```
{
  "transaction": {
    "time": "30/May/2023:16:24:54.554782 +0000",
    "transaction_id": "ZHYjVmYd9f-YI4qF-PtKfgAAAIA",
    "remote_address": "172.24.0.4",
    "remote_port": 38164,
    "local_address": "172.24.0.3",
    "local_port": 80
  },
  "request": {
    "request_line": "POST /auth/login_flow HTTP/1.1",
    "headers": {
      "Host": "modsecurity:80",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57",
      "Content-Length": "145",
      "Accept": "*/*",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "es",
      "Content-Type": "text/plain;charset=UTF-8",
      "Origin": "https://ha.asdasdasd.com.es",
      "Referer": "https://ha.asdasdasd.com.es/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fha.asdasdasd.com.es%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fha.asdasdasd.com.es%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9oYS5zdWJ6ZXJvY2xvdWQuY29tLmVzIiwiY2xpZW50SWQiOiJodHRwczovL2hhLnN1Ynplcm9jbG91ZC5jb20uZXMvIn0%3D",
      "Sec-Ch-Ua": "\"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "X-Forwarded-Host": "ha.asdasdasd.com.es",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Server": "fe88f12530b6",
      "X-Real-Ip": "10.10.10.23"
    },
    "body": [
      "{\"client_id\":\"https://ha.asdasdasdasd.com.es/\",\"handler\":[\"homeassistant\",null],\"redirect_uri\":\"https://ha.asdasdasdasd.com.es/?auth_callback=1\"}"
    ]
  },
  "response": {
    "protocol": "HTTP/1.1",
    "status": 200,
    "headers": {
      "Content-Length": "1358",
      "Content-Type": "text/plain; charset=utf-8"
    },
    "body": "Hostname: 50ada140cfd9\nIP: 127.0.0.1\nIP: 172.24.0.2\nRemoteAddr: 172.24.0.3:42962\nPOST /auth/login_flow HTTP/1.1\r\nHost: modsecurity:80\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57\r\nContent-Length: 145\r\nAccept: */*\r\nAccept-Language: es\r\nConnection: close\r\nContent-Type: text/plain;charset=UTF-8\r\nOrigin: https://ha.asdasdasd.com.es\r\nReferer: https://ha.asdasdasd.com.es/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fha.asdasdasd.com.es%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fha.asdasdasd.com.es%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9oYS5zdWJ6ZXJvY2xvdWQuY29tLmVzIiwiY2xpZW50SWQiOiJodHRwczovL2hhLnN1Ynplcm9jbG91ZC5jb20uZXMvIn0%3D\r\nSec-Ch-Ua: \"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nSec-Fetch-Dest: empty\r\nSec-Fetch-Mode: cors\r\nSec-Fetch-Site: same-origin\r\nX-Forwarded-For: 172.24.0.4\r\nX-Forwarded-Host: ha.asdasdasd.com.es, modsecurity:80\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: fe88f12530b6, localhost\r\nX-Real-Ip: 172.24.0.4\r\nX-Unique-Id: ZHYjVmYd9f-YI4qF-PtKfgAAAIA\r\n\r\n{\"client_id\":\"https://ha.asdasdasd.com.es/\",\"handler\":[\"homeassistant\",null],\"redirect_uri\":\"https://ha.asdasdasd.com.es/?auth_callback=1\"}"
  },
  "audit_data": {
    "messages": [
      "Warning. Match of \"within %{tx.allowed_request_content_type}\" against \"TX:content_type\" required. [file \"/etc/modsecurity.d/owasp-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"957\"] [id \"920420\"] [msg \"Request content type is not allowed by policy\"] [data \"|text/plain|\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/3.3.4\"] [tag \"modsecurity\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/255/153\"] [tag \"PCI/12.1\"]"
    ],
    "error_messages": [
      "[file \"apache2_util.c\"] [line 275] [level 3] [client 172.24.0.4] ModSecurity: Warning. Match of \"within %{tx.allowed_request_content_type}\" against \"TX:content_type\" required. [file \"/etc/modsecurity.d/owasp-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"957\"] [id \"920420\"] [msg \"Request content type is not allowed by policy\"] [data \"|text/plain|\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/3.3.4\"] [tag \"modsecurity\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/255/153\"] [tag \"PCI/12.1\"] [hostname \"modsecurity\"] [uri \"/auth/login_flow\"] [unique_id \"ZHYjVmYd9f-YI4qF-PtKfgAAAIA\"]"
    ],
    "handler": "proxy-server",
    "stopwatch": {
      "p1": 476,
      "p2": 748,
      "p3": 67,
      "p4": 381,
      "p5": 123,
      "sr": 61,
      "sw": 0,
      "l": 0,
      "gc": 0
    },
    "response_body_dechunked": true,
    "producer": [
      "ModSecurity for Apache/2.9.7 (http://www.modsecurity.org/)",
      "OWASP_CRS/3.3.4"
    ],
    "server": "Apache",
    "engine_mode": "ENABLED"
  }
}
```

I have tried several combinations in the file "REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf" but I only get errors
What is the right way to do it?
I would apreciate any help to learn how to whitelist, I have seen the example but nothing works using the conf file

The other problem I have is that I have been trying to map volumes to be able to edit the config files without success, what I'm doing wrong?
