### ISSUE TITLE
Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by git-SwitchBlade** [coreruleset/modsecurity-crs-docker#217]
Hi Community,

I have set up a docker container with nginx and modsecurity, with a nginx default.conf but when I try to reach http://localhost, I get `400 Resquest Code Request Header Or Cookie Too Large`, Below is the screenshot attached and my default.conf

![Screenshot from 2024-03-11 11-42-41](https://github.com/coreruleset/modsecurity-crs-docker/assets/85271575/5077988b-12d0-42af-8d41-de6ad73a8b62)

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
	modsecurity on;
        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;
        client_body_buffer_size     32k;
        client_header_buffer_size   8k;
        large_client_header_buffers 8 64k;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
	        # proxy_pass http://localhost:8080;
        	# proxy_http_version 1.1;
	        # proxy_set_header Upgrade $http_upgrade;
        	# proxy_set_header Connection 'upgrade';
	        # proxy_set_header Host $host;
        	# proxy_cache_bypass $http_upgrade;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
        #       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```
Below is the docker file used

```
version: "3"

services:
  nginx-modsec:
    build: owasp/modsecurity-crs:3.3.4-nginx-alpine-202301110601
    ports:
      - "80:80"
    environment:
      - MODSEC_AUDIT_ENGINE=on
      - MODSEC_AUDIT_LOG=/var/log/nginx/modsec_audit.log
      - MODSEC_RULE_ENGINE=DetectionOnly
      - MODSEC_AUDIT_LOG_PARTS=ABCEFHJKZ
    volumes:
      - ./default.conf:/etc/nginx/templates/conf.d/default.conf:ro
      - ./log:/var/log/nginx
```

Thanks in advanced for the help
