### ISSUE TITLE
generate-certificate exited with code 1

### ISSUE THREAD

**Issue by nurlanchip** [coreruleset/modsecurity-crs-docker#255]
hi everyone, I need help, I'm getting an error when running docker compose modsecurity-crs

```
modsec-apache     | /usr/local/bin/generate-certificate: generating new certificate
modsec-apache     | Warning: No -copy_extensions given; ignoring any extensions in the request
modsec-apache     | /usr/local/bin/generate-certificate: generated /usr/local/apache2/conf/server.key and /usr/local/apache2/conf/server.crt
modsec-apache     | 
modsec-apache exited with code 1
```

this is the docker compose from https://coreruleset.org/docs/deployment/install/
```

services:
  modsec-apache:
    container_name: modsec-apache-alpine
    image: owasp/modsecurity-crs:apache-alpine
    environment:
      SERVERNAME: modsec-apache-alpine
      BACKEND: "http://192.168.1.10:3000/"
      PORT: "80"
      MODSEC_AUDIT_ENGINE: On
      MODSEC_RULE_ENGINE: On
      BLOCKING_PARANOIA: 2
      ERRORLOG: "/var/log/modsec_error.json"
      ACCESSLOG: "/var/log/modsec_access.json"
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG_PARTS: ABDEFHIJZ
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.json"
      MODSEC_TMP_DIR: "/tmp"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      COMBINED_FILE_SIZES: "65535"
    volumes:
      - "/var/log/:/var/log/"
    ports:
      - "80:80"

  juiceshop_prod:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
```

**Comment by fzipi** [comment]
Hi @nurlanchip 

I see you are using port 80 there. The image was updated to run as an unprivileged user:
```
Both nginx and httpd containers now run with an unprivileged user. This means that we cannot bind to ports below 1024, so you might need to correct your PORT and SSL_PORT settings. Now the defaults for both nginx and httpd are 8080 and 8443.
```

**Comment by nurlanchip** [comment]
I have changed the port like this

```
services:
  modsec-apache:
    container_name: modsec-apache
    image: owasp/modsecurity-crs:apache
    environment:
      SERVERNAME: modsec-apache
      BACKEND: "http://192.168.1.10:3000"
      PORT: "8080"
      MODSEC_AUDIT_ENGINE: On
      MODSEC_RULE_ENGINE: On
      BLOCKING_PARANOIA: 2
      ERRORLOG: "/var/log/modsec_error.json"
      ACCESSLOG: "/var/log/modsec_access.json"
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG_PARTS: ABDEFHIJZ
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.json"
      MODSEC_TMP_DIR: "/tmp"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      COMBINED_FILE_SIZES: "65535"
    volumes:
      - "/var/log/:/var/log/"
    ports:
      - "80:8080"

  juiceshop_prod:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
```

still error like this

```
modsec-apache     | /usr/local/bin/generate-certificate: generating new certificate
modsec-apache     | Warning: No -copy_extensions given; ignoring any extensions in the request
modsec-apache     | /usr/local/bin/generate-certificate: generated /usr/local/apache2/conf/server.key and /usr/local/apache2/conf/server.crt
modsec-apache     | AH00526: Syntax error on line 24 of /etc/modsecurity.d/modsecurity.conf:
modsec-apache     | ModSecurity: Failed to open the audit log file: /var/log/modsec_audit.json
modsec-apache exited with code 1
```
