### ISSUE TITLE
latest nginx-alpine tag is not working properly

### ISSUE THREAD

**Issue by fichte** [coreruleset/modsecurity-crs-docker#326]
in the following example this is a small docker stack with owasp/modsecurity-crs as proxy and portainer behind owasp/modsecurity-crs

the latest tag owasp/modsecurity-crs:4.10.0-nginx-alpine-202501270601 produces weird errors

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/2f03e857-a8f7-4011-8f2b-b8a5b9cfbb24" />

the previous tag owasp/modsecurity-crs:4.10.0-nginx-alpine-202501050801 works perfectly

<img width="1245" alt="Image" src="https://github.com/user-attachments/assets/cb81d680-8882-4c8f-a635-bf643e97e96a" />

it looks suspicious to me. both image are from the public docker registry. i dont have the time to debug this. i can assure that the config is exactly the same.

**Comment by theseion** [comment]
Thanks for the report @fichte. Unfortunately, I don't see any obvious issues when I run the image locally. If you could provide your configuration for your Portainer setup, I could try to replicate it.

Have you tried using the regular `nginx` image?

**Comment by Serverfrog** [comment]
I just had the same kind of problem for me. I was not running it on Portainer but on a Kubernetes Cluster.

The Problem was for me that, if the Response Content is above a Size (can't really tell what the minimum is, but should be above 4000 Characters), the First ~1080 Characters get "corrupted" in the sense that they will be some later content in there.

Thats result for example with a JSON response that wont start with `{` but with some later content and results in malformed JSON.
That also results in Content-Encoding errors with other Sources, where the Browser validates it (CSS, JS, etc).
Going back Versions fixed that for me, so it looks like this is really a problem with that build (i didn't changed anything beside the Image)

**Comment by fichte** [comment]
just open the developer console and go to http://localhost

working docker-compose.yml with previous tag

```
x-defaults: &default-settings
  environment:
    SERVERNAME: localhost
    PARANOIA: 1
    BLOCKING_PARANOIA: 1
    ANOMALY_INBOUND: 5
    ANOMALY_OUTBOUND: 4
    REPORTING_LEVEL: 2
  volumes:
    - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf

services:
  crs-nginx:
    environment:
      - BACKEND="http://portainer:9000"
    image: owasp/modsecurity-crs:4.10.0-nginx-alpine-202501050801
    ports:
      - "80:8080"
    <<: *default-settings

  portainer:
    image: portainer/portainer-ce:sts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

non working docker-compose.yml with latest version

```
x-defaults: &default-settings
  environment:
    SERVERNAME: localhost
    PARANOIA: 1
    BLOCKING_PARANOIA: 1
    ANOMALY_INBOUND: 5
    ANOMALY_OUTBOUND: 4
    REPORTING_LEVEL: 2
  volumes:
    - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf

services:
  crs-nginx:
    environment:
      - BACKEND="http://portainer:9000"
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - "80:8080"
    <<: *default-settings

  portainer:
    image: portainer/portainer-ce:sts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
