### ISSUE TITLE
REAL_IP_HEADER / REAL_IP_PROXY_HEADER doesnt work properly in 4.12.0-apache-202503230103

### ISSUE THREAD

**Issue by ednv** [coreruleset/modsecurity-crs-docker#349]
Hello.

My website is on AWS, behind a load balancer. Whoami :

```
Hostname: 651651651651
IP: 127.0.0.1
IP: 192.168.88.3
RemoteAddr: 192.168.88.2:58751
GET / HTTP/1.1
Host: azeazeazeaze.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: fr-FR,fr;q=0.9,es-ES;q=0.8,es;q=0.7,en;q=0.6
Cookie: __zlcmid=1QqnUU6qtLerEYQ
Priority: u=0, i
Sec-Ch-Ua: "Chromium";v="134", "Not:A-Brand";v="24", "Google Chrome";v="134"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Amzn-Trace-Id: Root=eauzgeuyazgeuyagzue
X-Forwarded-For: 1.2.3.4, 172.1.2.3
X-Forwarded-Host: auditeur-whoami.ilxb.fr
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: fze5f65zef
X-Real-Ip: 172.1.2.3
```

I am using this in docker-compose.yaml 

```
  waf:
    #image: owasp/modsecurity-crs:4.12.0-apache-202503230103
    image: owasp/modsecurity-crs:4.12.0-nginx-202503230103
    container_name: waf
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT
      - MODSEC_REQ_BODY_NOFILES_LIMIT=13107200
      - ERRORLOG=/var/tmp/waf.log
      - BACKEND=http://dummy
      - ALLOWED_REQUEST_CONTENT_TYPE=application/x-www-form-urlencoded|text/plain|multipart/form-data|multipart/related|text/xml|application/xml|application/soap+xml|application/json
      - MODSEC_DEBUG_LOGLEVEL=3
      - MODSEC_DEBUG_LOG=/var/tmp/debug.log
      - REAL_IP_HEADER=X-Forwarded-For
      - REAL_IP_PROXY_HEADER=X-Forwarded-For
    volumes:
      - ./config/_INIT_/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
```

REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf content :

```
SecRule REMOTE_ADDR "@ipMatch 1.2.3.4" \
     "id:1000,\
     phase:1,\
     pass,\
     nolog,\
     ctl:ruleEngine=Off"
```

But if i only replace image: owasp/modsecurity-crs:4.12.0-apache-202503230103 by image: owasp/modsecurity-crs:4.12.0-nginx-202503230103 it works as expected.

With apache, remote_addr is still 192.168.88.2:whatever and using apache won't replace 192.168.88.2:whatever by 1.2.3.4 but using nginx will do the replacement.

Your work is really appreciated.

Regards,
