### ISSUE TITLE
Overriding crs-setup.conf

### ISSUE THREAD

**Issue by Ben-Atherton** [coreruleset/modsecurity-crs-docker#39]
I am using this image but wish to override the crs-setup.conf file so that I can enable Application Specific Rule Exclusions, I have my docker-compose.yml file setup as below:

```
image: owasp/modsecurity-crs:v3.3.2-nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "./code:/code"
      - "./modsecurity/crs-setup.conf:/etc/modsecurity.d/owasp-crs/crs-setup.conf"
```

However the container goes into a reboot loop and the following errors are present in the logs:

```
sed: cannot rename /etc/modsecurity.d/owasp-crs/sedt1ZR5Z: Device or resource busy
sed: cannot rename /etc/modsecurity.d/owasp-crs/sedef3G25: Device or resource busy
sed: cannot rename /etc/modsecurity.d/owasp-crs/sedj26WEL: Device or resource busy
sed: cannot rename /etc/modsecurity.d/owasp-crs/sedu5ZwVq: Device or resource busy
```

Any ideas what I am doing wrong here or if this is a bug? There are no specific instructions in the readme about this.

Thanks in advance
