### ISSUE TITLE
Redirect issue with the owasp/modsecurity-crs:apache docker container

### ISSUE THREAD

**Issue by RALGIE** [coreruleset/modsecurity-crs-docker#40]
Hello,

I have an issue with the redirect. I have the following docker-compose file. 

```yml
version: "3.7"
services:
  apachecrs:
    container_name: apachecrs_waf
    image: owasp/modsecurity-crs:apache
    ports:
      - "443:443"
    restart: always
    environment:
      - PARANOIA=1
      - ANOMALYIN=5
      - ANOMALYOUT=2
      - LOGLEVEL=debug
      - ALLOWED_METHODS=GET POST HEAD OPTIONS
      - MAX_FILE_SIZE=5242880
      - PROXY=1
      - PORT=8080
      - SERVERNAME=192.168.2.52
      - BACKEND=http://192.168.2.52:8080
```
When I display the url https://localhost the login page is displayed. But when I login I'm redirected to an other page in my portal  https://localhost/main (http://192.168.2.52:8080/main). This redirect is not happening. I get an page could not be displayed. 

This is what I found in the logfile:
```[0m [Thu Jul 29 13:01:23.668624 2021] [socache_shmcb:debug] [pid 50:tid 139731190937344] mod_socache_shmcb.c(572): AH00837: socache_shmcb_remove (0x0e -> subcache 14)
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668649 2021] [socache_shmcb:debug] [pid 50:tid 139731190937344] mod_socache_shmcb.c(955): AH00852: possible match at idx=0, data=0
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668654 2021] [socache_shmcb:debug] [pid 50:tid 139731190937344] mod_socache_shmcb.c(960): AH00853: shmcb_subcache_remove removing matching entry
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668657 2021] [socache_shmcb:debug] [pid 50:tid 139731190937344] mod_socache_shmcb.c(586): AH00839: leaving socache_shmcb_remove successfully
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668671 2021] [ssl:info] [pid 50:tid 139731190937344] [client 172.19.0.1:48910] AH02008: SSL library error 1 in handshake (server localhost:443)
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668699 2021] [ssl:info] [pid 50:tid 139731190937344] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668714 2021] [ssl:info] [pid 50:tid 139731190937344] [client 172.19.0.1:48910] AH01998: Connection closed to child 142 with abortive shutdown (server localhost:443)
[36mapachecrs_waf |[0m [Thu Jul 29 13:01:23.668795 2021] [http2:debug] [pid 50:tid 139731190937344] h2_session.c(960): [client 172.19.0.1:48910] AH03200: h2_session(142,INIT,0): created, max_streams=100, stream_mem=32768, workers_limit=6, workers_max=37, push_diary(type=1,N=256)
```
What setting or other configuration am I missing to get this to work?
