### ISSUE TITLE
Regex could not be compiled

### ISSUE THREAD

**Issue by TafkaMax** [coreruleset/modsecurity-crs-docker#86]
Hi

I am trying to use a custom vhost.conf file and I mounted it at conf/extra/httpd-vhost.conf

```
  apache-modsecurity-proxy:
    container_name: apache-modsecurity-proxy
    hostname: apache-modsecurity-proxy
    image: owasp/modsecurity-crs:apache
    restart: unless-stopped
    volumes:
        - /opt/keycloak/apache_modsecurity/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        - /opt/keycloak/apache_modsecurity/server.crt:/usr/local/apache2/conf/server.crt
        - /opt/keycloak/apache_modsecurity/server.key:/usr/local/apache2/conf/server.key
        - /opt/keycloak/apache_modsecurity/log:/var/log/apache2
    ports:
        - "80:80"
        - "443:443"
    env_file:
      - '/opt/keycloak/apache_modsecurity/env-apache_modsecurity'
    networks:
      - keycloak-network
```

vhost.conf
```
# Ansible managed
# Apache VirtualHost configuration for both HTTP and SSL

# Expose endpoints according to the documentation: https://www.keycloak.org/server/reverseproxy
<LocationMatch "^/(realms|resources)/*">
    # Allow access to the public interfaces
    Require all granted
</LocationMatch>
<Location /robots.txt>
    # Allow access to the public interfaces
    Require all granted
</Location>

<LocationMatch "^/(admin|welcome|metrics|health)/?*">
    # restrict access to the management interfaces
    Order Deny,Allow
    Deny from all
    Allow from 127.0.0.1
    Allow from 192.168.0.0/16
</LocationMatch>


ProxyErrorOverride on
ProxyPass / ${BACKEND}/ disablereuse=on
ProxyPassReverse / ${BACKEND}/
ProxyPreserveHost ${PROXY_PRESERVE_HOST}
ProxyRequests off
ProxyTimeout ${PROXY_TIMEOUT}

RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy ${REMOTEIP_INT_PROXY}

RequestHeader set X-Forwarded-Proto "${REQ_HEADER_FORWARDED_PROTO}"
RequestHeader set X-Real-IP %{REMOTE_ADDR}s
RequestHeader set X-Unique-ID %{UNIQUE_ID}e

RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteEngine on
RewriteRule .* "${BACKEND_WS}%{REQUEST_URI}" [P]

ServerName ${SERVER_NAME}
ServerAdmin ${SERVER_ADMIN}

SSLProxyEngine ${PROXY_SSL}
SSLProxyVerify ${PROXY_SSL_VERIFY}
SSLProxyCheckPeerName ${PROXY_SSL_CHECK_PEER_NAME}
SSLProxyCACertificateFile ${PROXY_SSL_CA_CERT}

UseCanonicalName on

<VirtualHost *:${PORT}>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
    RewriteCond %{ENV:APACHE_ALWAYS_TLS_REDIRECT} on
    RewriteRule ^(.*)$ https://%{SERVER_NAME}:${SSL_PORT}$1 [L,R=301]
</VirtualHost>

<VirtualHost *:${SSL_PORT}>
  Protocols ${H2_PROTOCOLS}
  SSLEngine ${SSL_ENGINE}
  SSLCertificateFile ${PROXY_SSL_CERT}
  SSLCertificateKeyFile ${PROXY_SSL_CERT_KEY}
</VirtualHost> 
```

```
AH00526: Syntax error on line 15 of /usr/local/apache2/conf/extra/httpd-vhosts.conf:
Regex could not be compiled
```

Is there an issue in my regex?
