### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by igoooor** [coreruleset/modsecurity-crs-docker#91]
Hello,

I am using `owasp/modsecurity-crs:apache-alpine` in my kubernetes cluster.
The image is configured in a `Deployment` and I have the following liveness & readiness defined:
```
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: healthz
```

`BACKEND` is pointing to a "dummy" nginx always returning `200`
Everything seems to work well, but from time to time, "legit" requests as well as the two healthchecks above give the following error:
`context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
That's all the information I have. Did anyone else encounter that issue? Do you have some best practice to follow?
Thanks for your time and support
